[workspace]
members = [
    "core-sdk",
    "extended-sdk",
    "uci-engine",
    "tuning",
    "referee",
    "playground",
    "benchmarking",
    "tests",
    "experimental"
]
[profile.dev]
opt-level = 1
[profile.release]
opt-level = 3
lto = true
debug = false